spring:
  cloud:
    gateway:
      routes:
        - id: llm-proxy
          uri: https://api.deepseek.com/v1/chat/completions
          predicates:
            - Path=/v1/chat/completions
        - id: sse-proxy
          uri: http://localhost:8080
          predicates:
            - Path=/sse,/mcp/message
server:
  port: 8888