spring:
  main:
    web-application-type: none
  application:
    name: sse-mcp-client
  ai:
#    dashscope:
#      api-key: your-api-key
    openai:
      api-key: your-api-key
      chat:
        options:
          model: deepseek-chat
      base-url: https://api.deepseek.com
      embedding:
        enabled: false
    mcp:
      client:
        sse:
          connections:
            weather-server:
              url: http://localhost:8080
#              url: http://localhost:8888