spring:
  ai:
    dashscope:
      # 配置通义千问API密钥
      api-key: your-api-key
    mcp:
      client:
        stdio:
          # 指定MCP服务器配置文件路径（推荐）
          servers-configuration: classpath:/mcp-servers-config.json