spring:
  main:
    web-application-type: none
  application:
    name: agent-test
  ai:
    openai:
      api-key: your-api-key
      chat:
        options:
          model: deepseek-chat
      base-url: https://api.deepseek.com
      #base-url: http://localhost:8888
      embedding:
        enabled: false