spring:
  main:
    web-application-type: none
  application:
    name: agent-test
  ai:
    openai:
      api-key: sk-7d22f0384b2341448cecd8e2214f1eea
      chat:
        options:
          model: deepseek-chat
      base-url: https://api.deepseek.com
      embedding:
        enabled: false